# Generated by Django 2.2.3 on 2019-07-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('subpart_inner', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('subpart_outer', models.URLField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=40)),
            ],
        ),
    ]
